mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /ui
secret: ''
proxies: []
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
- name: AUTO
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: []
- name: AI
  type: select
  proxies: []
- name: VIDEO
  type: select
  proxies: []
- name: Paid-Auto
  type: url-test
  use: []
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: Free-Auto
  type: url-test
  use: []
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
- name: Proxy
  type: select
  proxies:
  - Paid-Auto
  - Free-Auto
  - DIRECT
rules:
- GEOIP,CN,DIRECT,no-resolve
- MATCH,Proxy
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
  - 223.5.5.5
  - 8.8.8.8
proxy-providers: {}
