mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /ui
secret: ''
proxies: []
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - AUTO
  - DIRECT
- name: AUTO
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: []
- name: AI
  type: select
  proxies: []
- name: VIDEO
  type: select
  proxies: []
rules:
- DOMAIN-SUFFIX,openai.com,AI
- DOMAIN-SUFFIX,chatgpt.com,AI
- DOMAIN-SUFFIX,youtube.com,VIDEO
- DOMAIN-SUFFIX,googlevideo.com,VIDEO
- MATCH,PROXY
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
  - 223.5.5.5
  - 8.8.8.8
