mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /ui
secret: ''
proxies: []
proxy-groups:
- name: US-Auto
  type: url-test
  filter: (?i)(\bUS\b|United States|America|美国|美西|美东|洛杉矶|圣何塞|硅谷|西雅图|达拉斯|芝加哥|纽约|华盛顿)
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: &id001
  - DIRECT
- name: Free-Auto
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies: *id001
- name: Google
  type: fallback
  proxies:
  - US-Auto
  - REJECT
  url: https://www.gstatic.com/generate_204
  interval: 300
- name: Proxy
  type: select
  proxies:
  - Free-Auto
  - US-Auto
  - DIRECT
rules:
- RULE-SET,geoip-private,DIRECT,no-resolve
- RULE-SET,geosite-cn,DIRECT
- RULE-SET,geosite-google,Google
- RULE-SET,geosite-youtube,Google
- DOMAIN-SUFFIX,google.com,Google
- DOMAIN-SUFFIX,google.com.hk,Google
- DOMAIN-SUFFIX,googleapis.com,Google
- DOMAIN-SUFFIX,gstatic.com,Google
- DOMAIN-SUFFIX,googleusercontent.com,Google
- DOMAIN-SUFFIX,ggpht.com,Google
- DOMAIN-SUFFIX,1e100.net,Google
- DOMAIN-SUFFIX,youtube.com,Google
- DOMAIN-SUFFIX,googlevideo.com,Google
- DOMAIN-SUFFIX,ytimg.com,Google
- DOMAIN-SUFFIX,youtube-nocookie.com,Google
- DOMAIN-SUFFIX,google-analytics.com,Google
- DOMAIN-SUFFIX,googletagmanager.com,Google
- DOMAIN-SUFFIX,googlesyndication.com,Google
- DOMAIN-SUFFIX,googleadservices.com,Google
- DOMAIN-SUFFIX,gmail.com,Google
- DOMAIN-SUFFIX,googlesource.com,Google
- RULE-SET,geosite-gfw,Proxy
- GEOIP,CN,DIRECT,no-resolve
- MATCH,Proxy
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
  - 223.5.5.5
  - 8.8.8.8
proxy-providers: {}
rule-providers:
  geosite-google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.yaml
    path: ./ruleset/geosite-google.yaml
    interval: 86400
  geosite-youtube:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.yaml
    path: ./ruleset/geosite-youtube.yaml
    interval: 86400
  geosite-gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/gfw.yaml
    path: ./ruleset/geosite-gfw.yaml
    interval: 86400
  geosite-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.yaml
    path: ./ruleset/geosite-cn.yaml
    interval: 86400
  geoip-private:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.yaml
    path: ./ruleset/geoip-private.yaml
    interval: 86400
